# Set the prefix key to Ctrl + t instead of Ctrl + b
unbind C-b
set-option -g prefix C-t
bind C-t send-prefix
set-option -sa terminal-overrides ",xterm*:Tc"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other useful settings
set-option -g mouse on                                     # Enable mouse support
set-option -g history-limit 5000                           # Set history scrollback limit
set-option -g base-index 1                                 # Start window numbering at 1
set-window-option -g pane-base-index 1                     # Start pane numbering at 1

# Key bindings for window management
bind -n M-c new-window -c "#{pane_current_path}"           # Alt + c to create a new window in the same directory
bind -n M-n next-window                                    # Alt + n to go to the next window
bind -n M-p previous-window                                # Alt + p to go to the previous window
bind -n M-w kill-window                                    # Alt + w to close the current window
bind -n M-e command-prompt "rename-window '%%'"            # Rename window

# Key bindings for pane splitting
bind -n M-C-l split-window -h -c "#{pane_current_path}"    # Alt + Ctrl + l to split pane vertically in the same directory
bind -n M-C-k split-window -v -c "#{pane_current_path}"    # Alt + Ctrl + k to split pane horizontally in the same directory
bind -n M-m resize-pane -Z

# Pane navigation using Alt + Vim keys (h/j/k/l)
bind -n M-h select-pane -L                                 # Alt + h to move to the left pane
bind -n M-j select-pane -D                                 # Alt + j to move to the pane below
bind -n M-k select-pane -U                                 # Alt + k to move to the pane above
bind -n M-l select-pane -R                                 # Alt + l to move to the right pane

# For Session
bind -n M-s choose-tree
bind -n M-d detach-client
bind -n M-N switch-client -n
bind -n M-P switch-client -p

run '~/.tmux/plugins/tpm/tpm'
